- data/duke.txt
- src/main/java/duke/Duke.java
- src/main/java/duke/Reminder.java
- src/main/java/duke/command/RemindCommand.java
- src/main/java/duke/core/Ui.java
- src/main/java/duke/task/Deadline.java
- src/main/java/duke/task/Event.java
- src/main/java/duke/task/Task.java
The reminder function will keep repeating the task reminder every 20 seconds if the duration between the current time and the deadline is less than one day. To stop the reminder the user have to mark the task as done.
> added the reminder function

- src/main/java/duke/command/ViewCommand.java
- src/main/java/duke/core/Parser.java
- src/main/java/duke/core/Ui.java
By using command [view dd/mm/yyyy] to show a list of tasks falling on specified date.
> added B-ViewSchedules

- src/main/java/duke/task1/PersonalTask.java
- src/main/java/duke/task1/StandardTask.java
- src/main/java/duke/task1/Task.java
New task classes, no new added functionality yet.
> beginnings of new Task classes for skeleton Dukepital

- src/main/java/duke/Duke.java
- src/main/java/duke/command/ExitCommand.java
- src/main/java/duke/core/CommandManager.java
- src/main/java/duke/core/DateTimeParser.java
- src/main/java/duke/core/Storage.java
- src/main/java/duke/core/Ui.java
- src/main/java/duke/patient/Patient.java
- src/main/java/duke/patient/PatientList.java
- src/main/java/duke/storage/PatientStorage.java
- src/main/java/duke/task/PersonalTask.java
- src/main/java/duke/task/StandardTask.java
- src/main/java/duke/task/Task.java
with minor error such as JavaDoc not written and indentation error for commenting
> reduced checkstylemain error to 9 

- src/main/java/duke/core/CommandManager.java
> Fixed minor bug on wrong output

- data/patients.csv
- src/main/java/duke/command/UpdateCommand.java
- src/main/java/duke/command/UpdatePatientCommand.java
- src/main/java/duke/core/CommandManager.java
- src/main/java/duke/core/Ui.java
- src/main/java/duke/patient/Patient.java
- src/main/java/duke/patient/PatientList.java
update patient <ID> <Information type to be updated> <updated value> 
eg. update patient 5 name Jay Chou
> added UpdateCommand to update existing patient information .

- src/main/java/duke/command/AddPatientCommand.java
- src/main/java/duke/command/AddStandardTaskCommand.java
- src/main/java/duke/core/CommandManager.java
- src/main/java/duke/core/Parser.java
Handles parsing of user input for the 'add patient' and 'add task' command, as well as some reformatting of the AddPatientCommand and AddStandardTaskCommand in order to standardize the behavior of the classes.
The CommandManager still needs to distinguish whether the case is 'add patient' or 'add task', but the same method can be called to handle either case.
Relevant to Task #96
> Parser Class 'add' method

- data/standardTasks.csv
- src/main/java/duke/storage/TaskStorage.java
- src/main/java/duke/task/Task.java
- src/main/java/duke/task/TaskManager.java
Currently there is no unique id for each individual task. However, a task id is necessary in order to assign a task to patient. I add the id column in the standardTask.csv file. When a new task is added, an id will be added as well.
> Add a unique id for every standard task

- src/main/java/duke/command/AssignTaskToPatientCommand.java
- src/main/java/duke/core/CommandManager.java
- src/main/java/duke/core/Parser.java
Specifically handling cases where input contains key phrase: 'assign by id:`--will implement a more UI-friendly version later.
Had to revise a few sections of AssignTaskToPatientCommand class so that its constructor had more consistent behavior, and did not use finalPatientTask method as a parser. 
PR is relevant to task #98
> Implementation of 'assign' method in Parser class

- src/main/java/duke/command/DeletePatientCommand.java
- src/main/java/duke/command/DeleteTaskCommand.java
- src/main/java/duke/core/CommandManager.java
- src/main/java/duke/core/Parser.java
- src/main/java/duke/core/Ui.java
Meant to handle currently available cases of `delete patient` and `delete task`: 
- `delete patient #<patient_id>`
- `delete patient <patient_name>`
- `delete task #<task_id>`
- `delete task <task_description>`
Relevant to #113 .
> Implemented .parseDeletePatient() and .parseDeleteTask() methods for Parser class

- data/patients.csv
- src/main/java/duke/command/UpdatePatientCommand.java
- src/main/java/duke/core/CommandManager.java
- src/main/java/duke/core/Parser.java
- src/main/java/duke/core/Ui.java
User can update patient using command "update patient #<id> <Name/NRIC/Room> <New info>"
> Fix bug of update patient command

- src/main/java/duke/command/UpdateTaskCommand.java
Fix the bug #139 
Have corrected the DukeException of update task command.
> Correct update task command DukeException

- src/main/java/duke/core/Parser.java
- src/test/java/duke/core/ParserTest.java
Finalizing the types of output the Parser provides for the deleteAssignedTasks(), and implementing more thorough test cases for the class.
Relevant to #95 .
> Parser Update for deleteAssignedTasks() change requests + JUnits

- src/main/java/duke/commands/task/DeleteTaskCommand.java
- src/main/java/duke/models/assignedtasks/AssignedTaskManager.java
Fixed a minor bug on delete assigned task by task id,
now the delete process will not terminate once a task with the matched id found,
instead it will try to search and delete all the tasks with the matched id @kkeejjuunn
> Fixed a minor bug on delete assigned task by task id

- src/main/java/duke/commands/patient/FindPatientCommand.java
- src/main/java/duke/models/patients/PatientManager.java
Current find patient command will only list the patient with the exact same name as the input will be listed out. To be more user-friendly, all the patients' name contain the input will be listed out.
> Update find patient command so that if any patients' name contain the input name will be listed out.

- src/main/java/duke/commands/CommandManager.java
- src/main/java/duke/commands/task/FindTaskCommand.java
- src/main/java/duke/models/tasks/TaskManager.java
- src/main/java/duke/util/Ui.java
> Allow user to find task by id or description.

- src/main/java/duke/util/Ui.java
> Fix code style from pevious PR to pass Travis

- src/main/java/duke/commands/assignedtask/AssignDeadlineTaskCommand.java
- src/main/java/duke/commands/assignedtask/AssignPeriodTaskCommand.java
- src/main/java/duke/commands/assignedtask/DeleteAssignedTaskCommand.java
- src/main/java/duke/commands/assignedtask/FindAssignedTaskCommand.java
- src/main/java/duke/models/assignedtasks/AssignedTask.java
- src/main/java/duke/models/assignedtasks/AssignedTaskManager.java
- src/main/java/duke/models/assignedtasks/AssignedTaskWithDate.java
- src/main/java/duke/models/assignedtasks/AssignedTaskWithPeriod.java
- src/main/java/duke/storages/StorageManager.java
- src/main/java/duke/util/mementopattern/MementoManager.java
- src/main/java/duke/util/mementopattern/MementoParser.java
BUGS FIX: 
1. a bug was found inside the **StorageManager** causing the storage saving system to save both patient Id and task Id as the same. (Fixed)
2.a bug was found inside the **StorageManager**  causing the storage loading system not loading the unique Id, instead it will regenerate the unique id every time. (Fixed)
3.one exception is not properly handled in the **DeleteAssignedTasks** (Fixed)
4.a bug was found in the **FindAssignedTasksCommand** a patient id is passed into a **TaskManager** (FIXED)
5.Same assigned task can be assigned with the same time period or deadline (Fixed)
New Bugs spotted and has been fixed:
1. **UndoParser** is not catching the command properly, will be fixed soon. (Fixed)
2.The **MementoManger** is previously pop, and add on different side of the …
> BUG fix on some critical problems & data structure improvement

- build.gradle
- src/main/java/duke/commands/patient/AddPatientCommand.java
- src/main/java/duke/commands/patient/DeletePatientCommand.java
- src/main/java/duke/commands/patient/FindPatientCommand.java
- src/main/java/duke/commands/patient/UpdatePatientCommand.java
- src/main/java/duke/commands/task/DeleteTaskCommand.java
- src/main/java/duke/commands/task/FindTaskCommand.java
- src/main/java/duke/commands/task/UpdateTaskCommand.java
- src/main/java/duke/exceptions/DukeException.java
- src/main/java/duke/util/Log4jLogger.java
- src/main/resources/log4j2.properties
All the DukeException thrown in the add/update/delete patient and task command will be logged into a log file called exception.log .
> Implement logger for all patient and task related command.

- src/main/java/duke/gui/MainWindow.java
- src/main/resources/view/MainWindow.fxml
solved a bug for PieChart and BarChart are not functioning if the amount of command in counter.csv is not matched with the hard coded command object in piechart and barchart code.
Here is what i did to solve the problem : 
**For PieChart**
**For BarChart**
> B improve on statistic code

- build.gradle
- src/main/java/duke/gui/MainWindow.java
- src/main/resources/view/MainWindow.fxml
To resolve #191 ,
I have implemented Auto Completion when typing commands in the Command box. 
Basically , when user are typing commands in dukepital, there will be suggestion listed to enable user to choose whether he/she wants to complete the command with the suggested word.
For example , when user want to add a task , first he have to type 'a'  for add key word , the following will appear when 'a' is entered :
This suggests all the keyword with 'a' in the them. At this point of time , user can choose 'add' from the list by using mouse click or pressing enter key from keyboard.
Then for demostration purpose, enter the next letter 'd' : 
P.S. I have also added Undo button Here
> Implemented auto completion with ControlFX

- src/main/java/duke/commands/functional/HelpCommand.java
- src/main/java/duke/util/Ui.java
Changed output of HelpCommand in order to keep command listings up to date. Commands provided should align with what is in the User Guide as of 30-10-19.
> Help Guide update

- build.gradle
- src/main/java/duke/gui/MainWindow.java
I have found out that our generated Jar file are not working in both terminal and when double clicking on it. 
Here is my solution to resolve this issue:
The main reason is due to the path provided as parameter into our Duke's constructor in MainWindow.Class  are not the absolute path of our data file. Hence , no data is loaded when jar file is executing which result to GUI not displaying.
After adding the following code below , the jar file is working perfectly for both executing in terminal as well as double clicking it. 
The details of what "user.dir" is [here ](https://stackoverflow.com/questions/16239130/java-user-dir-property-what-exactly-does-it-mean)
> Fixed Jar file path problem

- src/main/java/duke/commands/functional/HelpCommand.java
- src/main/java/duke/gui/HelpBox.java
- src/main/java/duke/gui/MainWindow.java
- src/main/java/duke/util/Ui.java
- src/main/resources/view/HelpBox.fxml
- src/main/resources/view/MainWindow.fxml
Fixed readability for reference during testing dry runs. ScrollPane implemented to allow content spacing to be greater.
Enhancement to #186 .
> Help Guide Improvements

- src/main/java/duke/commands/patient/AddPatientCommand.java
- src/main/java/duke/models/patients/PatientManager.java
> Implement the check of name, NRIC, room number while adding a new patient.

- src/main/java/duke/models/patients/PatientManager.java
- src/test/java/duke/models/patients/PatientManagerTest.java
> Add JUnit test for PatientManager.

- data/patientsTasks.csv
- data/standardTasks.csv
- src/main/java/duke/gui/MainWindow.java
Added more meaningful names/information, added more assigned tasks, etc. 
Also updated UpcomingTask GUI to handle bug involving repeated tasks after Dukepital's data was altered.
> Populating data and fixing bug within UpcomingTasks's GUI portion

- src/main/java/duke/commands/CommandManager.java
- src/main/java/duke/commands/functional/PieChartCommand.java
- src/main/java/duke/gui/MainWindow.java
- src/main/java/duke/gui/PieChartBox.java
- src/main/java/duke/models/counter/Counter.java
Enhanced AutoCompletion as well . Fixed issue #223
> added "piechart" command to show piechart in a new window.

- src/test/java/duke/models/tasks/TaskManagerTest.java
Increase the coverage of TaskManager from 80% to 97%.
> Increase TaskManagerTest coverage.

- src/main/java/duke/commands/patient/UpdatePatientCommand.java
- src/main/java/duke/models/patients/PatientManager.java
- src/test/java/duke/models/patients/PatientManagerTest.java
> Check if the room/nric is empty while adding or updating a patient.

- src/main/java/duke/commands/CommandManager.java
- src/main/java/duke/commands/functional/HelpCommand.java
- src/main/java/duke/gui/MainWindow.java
- src/test/java/duke/commands/CommandManagerTest.java
- src/test/java/duke/commands/HelpCommandTest.java
- src/test/java/duke/util/ParserTest.java
Altered MainWindow slightly to handle updates to AssignedTask information within the Upcoming Tasks tab. Added/updated test classes to verify positive tests; will add negative tests if time allows.
> Dynamic Update for Upcoming Tasks GUI + JUnits for ParserTest, CommandManager, and HelpCommand

- src/main/java/duke/commands/CommandManager.java
- src/main/java/duke/commands/functional/BarChartCommand.java
- src/main/java/duke/gui/BarChartBox.java
- src/main/java/duke/gui/MainWindow.java
- src/main/java/duke/gui/PieChartBox.java
- src/main/java/duke/models/counter/Counter.java
- src/main/java/duke/util/ShortCutter.java
- src/main/resources/view/MainWindow.fxml
- src/test/java/duke/models/counter/CounterTest.java
- src/test/java/duke/util/ShortCutterTest.java
Fixed bug in issue #228 , added Barchartcommand which enable to use it in CLI.
> Make a few minor changes and bug fixed 

- src/main/java/duke/commands/CommandManager.java
- src/main/java/duke/util/TypoCorrector.java
- src/test/java/duke/util/TypoCorrectorTest.java
Update the API provided by TypoCorrector with Junit test cases.
Sample Usage of TypoCorrector
```
TypoCorrector typoCorrector = new TypoCorrector(UserInputCommand);
If (typoCorrector.isCommandCorrected()){
//Request for user confirmation[Y/N] to approve the correction
UserInputCommand = typoCorrector.getCorrecedCommand();
}
```
> Update TypoCorrector with Junit Test

- src/test/java/duke/models/assignedtasks/AssignedTaskManagerTest.java
- src/test/java/duke/util/mementopattern/MementoManagerTest.java
add junit test for assignedTaskManager and mementoManager
> add junit test for assignedTaskManager and mementoManager

- README.adoc
- docs/ContactUs.adoc
Credit the source of Log4j library. 
Added Contact Us.
Added travis check status.
> Update ReadMe with the travis check and added contact us.

- src/main/java/duke/Duke.java
- src/main/java/duke/Launcher.java
- src/main/java/duke/Main.java
- src/main/java/duke/commands/CommandManager.java
- src/main/java/duke/commands/gui/ClearFilterCommand.java
- src/main/java/duke/commands/gui/FilterCommand.java
- src/main/java/duke/commands/gui/ShowAssignedTasksCommand.java
- src/main/java/duke/commands/gui/ShowHelpGuideCommand.java
- src/main/java/duke/commands/gui/ShowPatientsCommand.java
- src/main/java/duke/commands/gui/ShowTasksCommand.java
- src/main/java/duke/commands/gui/ShowTodayCommand.java
- src/main/java/duke/commands/gui/ShowTomorrowCommand.java
- src/main/java/duke/gui/MainWindow.java
- src/main/java/duke/util/DukeUi.java
- src/main/java/duke/util/TypoCorrector.java
- src/main/resources/view/MainWindow.fxml
Implemented following commands to manipulate GUI
1. show tasks
2. show patients
3. show assigned tasks
4. show help guide
5. show today 
6. show tomorrow 
5. filter: `<content>`
6. clear filter
> Implemented GUI commands to manipulate Filter/Switching tables/HelpGuide/Today or Tomorrow tasks

- src/main/java/duke/gui/MainWindow.java
- src/main/java/duke/util/TypoCorrector.java
- src/test/java/duke/util/TypoCorrectorTest.java
> Fix typo corrector

- src/main/java/duke/Duke.java
- src/main/java/duke/Main.java
- src/main/java/duke/util/StartUpData.java
Implemented with testing instances in mind; uploads around 20 data items into Duke to prevent testers from having to populate the program with data themselves, rather than going straight into testing.
Relevant to Issue #273 .
> Pre-populating Data when data files are empty
